apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: talk-plus-plus-production

namespace: talk-plus-plus-prod

resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: talk-plus-plus
    path: production-security-patch.yaml

images:
  - name: talk-plus-plus
    newTag: main-latest

replicas:
  - name: talk-plus-plus
    count: 5

commonLabels:
  environment: production
  tier: prod

commonAnnotations:
  environment: production
  contact: sre@talk-plus-plus.com
  oncall: pager-duty-integration

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - RUST_ENV=production
      - ENVIRONMENT=production
      - DEBUG_MODE=false
      - METRICS_ENABLED=true
      - TRACING_ENABLED=true

secretGenerator:
  - name: vault-config
    behavior: merge
    literals:
      - VAULT_ADDR=https://vault.talk-plus-plus.com:8200
      - VAULT_ROLE=talk-plus-plus-prod
      - VAULT_NAMESPACE=prod 