name: ✨ Feature Request
description: Suggest a new feature or enhancement for Talk++ AI Middleware Platform
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand your idea and its potential impact.

  - type: textarea
    id: summary
    attributes:
      label: 💡 Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        As a [user type], I want [goal] so that [benefit].
        
        Current situation: [describe current limitations]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 🔧 Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        How should this feature work?
        What should the user experience be like?
        Any specific technical requirements?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 📦 Affected Component
      description: Which component would this feature primarily affect?
      options:
        - "JARVIS Cognitive Core"
        - "Frontend (React)"
        - "Desktop App (Electron)"
        - "API Server"
        - "MCP Hub"
        - "Vector Database"
        - "CUDA Processor"
        - "External Services"
        - "Infrastructure/Deployment"
        - "Documentation"
        - "Multiple Components"
        - "New Component"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my use case"
        - "High - Would significantly improve my workflow"
        - "Medium - Nice to have improvement"
        - "Low - Minor enhancement"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🔨 Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Simple - Small change or addition"
        - "Moderate - Requires some new code/integration"
        - "Complex - Major feature requiring significant work"
        - "Unknown - Not sure about implementation complexity"
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 🔀 Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - Alternative approach A: [description]
        - Alternative approach B: [description]
        - Current workaround: [if any]

  - type: textarea
    id: examples
    attributes:
      label: 📋 Examples and Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example 1: [scenario and expected behavior]
        Example 2: [scenario and expected behavior]
        
        Similar features in other tools: [if any]

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups or Wireframes
      description: |
        If applicable, add mockups, wireframes, or visual examples.
        You can drag and drop images here or provide links.
      placeholder: Drag and drop images or provide links...

  - type: checkboxes
    id: implementation
    attributes:
      label: 🛠️ Implementation Considerations
      description: Check all that apply
      options:
        - label: This feature should maintain backward compatibility
        - label: This feature may require database schema changes
        - label: This feature may require API changes
        - label: This feature may require UI/UX changes
        - label: This feature may affect performance
        - label: This feature may require new dependencies
        - label: This feature may need security review

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] User can [specific action]
        - [ ] System responds with [expected behavior]
        - [ ] Feature works on [platforms/browsers]
        - [ ] Documentation is updated
        - [ ] Tests are included

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to work on implementing this feature
        - label: I can help with design/planning
        - label: I can help with testing
        - label: I can help with documentation
        - label: I'm available for feedback and review

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please check all that apply
      options:
        - label: I have searched existing issues and PRs to avoid duplicates
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
        - label: I have considered the impact on existing functionality
          required: true
        - label: I have provided specific use cases and examples
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        🚀 **Ready to contribute?** Check out our [Contributing Guide](CONTRIBUTING.md)
        
        💬 **Want to discuss first?** Join our community discussions or reach out to the team at features@talk-plus-plus.com 