# secrets.yaml - Template for Talk++ secrets
# Copy to secrets-local.yaml and fill in actual values
# DO NOT commit actual secrets to version control

apiVersion: v1
kind: Secret
metadata:
  name: talkpp-secrets
  namespace: talkpp
  labels:
    app.kubernetes.io/name: talkpp
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials
  database-url: "postgresql://talkpp:CHANGE_ME@postgresql:5432/talkpp"
  database-username: "talkpp"
  database-password: "CHANGE_ME"
  
  # JWT secret for authentication
  jwt-secret: "CHANGE_ME_TO_RANDOM_STRING"
  
  # Service API keys
  sendgrid-api-key: "CHANGE_ME"
  sendgrid-from-email: "noreply@yourdomain.com"
  
  twilio-account-sid: "CHANGE_ME"
  twilio-auth-token: "CHANGE_ME"
  twilio-from-number: "+1234567890"

---
# Example of how to create secrets from command line:
# kubectl create secret generic talkpp-secrets \
#   --from-literal=database-url="postgresql://user:pass@postgresql:5432/talkpp" \
#   --from-literal=jwt-secret="your-random-jwt-secret" \
#   --from-literal=sendgrid-api-key="your-sendgrid-key" \
#   --from-literal=twilio-account-sid="your-twilio-sid" \
#   --from-literal=twilio-auth-token="your-twilio-token" \
#   --namespace=talkpp

# Or create from .env file:
# kubectl create secret generic talkpp-secrets \
#   --from-env-file=.env \
#   --namespace=talkpp 