[package]
name = "cognitive-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
petgraph = { workspace = true }
futures = { workspace = true }
crossbeam = { workspace = true }

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs" 